### ISSUE TITLE
Wrong description for wp1-0.8 nopic

### ISSUE THREAD

**Issue by tbertels** [kiwix/maintenance#1]
The current description is the same as for wp1-0.8: "Wikipedia 45.000 best articles with pictures"
It should be "Wikipedia 45.000 best articles without pictures"

https://github.com/kiwix/maintenance/blob/4b44b184b9193cc640d1d19b71ac7a6df1a971c7/mwoffliner/mwoffliner3_dump.sh#L41

**Comment by kelson42** [comment]
@tbertels yes thx, I just have fixed it.
