### ISSUE TITLE
Are the mwoffliner scripts really the scripts used to generate Kiwix files?

### ISSUE THREAD

**Issue by bradyhunsaker** [kiwix/maintenance#10]
Underlying goal: When debugging, I sometimes want to determine the real commands used for a failing build.

I ask because mwmatrixoffliner has a miscapitalized parameter --mwURL, while mwoffliner and these scripts use --mwUrl.
I'm about to change mwmatrixoffliner to match.

But as I understand it, these commands should not even work with mwmatrixoffliner due to the difference.  It doesn't work on my command line when I try to use --mwUrl as these scripts do.

Are these the real scripts used?

**Comment by kelson42** [comment]
Yes, they are. I have no clue why it works... but it works at least until really recently. This is maybe due to certain version of nodejs... Anyway, good idea to fix the pb, seems better time invested than trying to understand this oddity.
