### ISSUE TITLE
Include category in library.kiwix.org.xml

### ISSUE THREAD

**Issue by rgaudin** [kiwix/maintenance#100]
Source catalog should now indicate the category for candidate ZIMs according to [this list](https://github.com/kiwix/kiwix-tools/issues/317) (to start from).

It is expected that kiwix-published ZIMs will now include a `_category` tag to ease with the automation of our current ZIM portfolio.

**Comment by kelson42** [comment]
Done with https://github.com/kiwix/kiwix-lib/pull/459
