### ISSUE TITLE
Remove a few ZIM files from download.kiwix.org

### ISSUE THREAD

**Issue by kelson42** [kiwix/maintenance#101]
* nodet if there is a mini
* novid if there is a maxi

**Comment by kelson42** [comment]
@Popolechien @rgaudin I'm thinking of renaming all "old" files on download.kiwix.org like this:
* `nodet` to `mini`
* `novid` to `maxi`

Would you support this move?

**Comment by Popolechien** [comment]
Of course I do.

**Comment by rgaudin** [comment]
Yes, I think the only drawback would be the timestamp of the files but given we have the creation date (month) in the filename we would still be able to differentiate old and recent ones.

**Comment by kelson42** [comment]
@rgaudin  Here is what I want to run in `/data/download/zim`:
```
for I in $(find . -name "*_nodet_*.zim"); do N=$(echo $I | sed 's/_nodet/_mini/'); if [ -e $N ]; then rm $I; else mv $I $N; fi; done
for I in $(find . -name "*_novid_*.zim"); do N=$(echo $I | sed 's/_novid/_maxi/'); if [ -e $N ]; then rm $I; else mv $I $N; fi; done
```

The redirects to maintain on certain backward compatibility on old styled permalinks is here:
https://github.com/kiwix/maintenance/commit/71ca216859c63175fc806f0f813ecba41b3951f3

Does it looks good for you?

**Comment by kelson42** [comment]
This has been done, a few tumults might happen in the next 2 hours, but there is nothing more we can do on our side.
