### ISSUE TITLE
Set up a releases feed

### ISSUE THREAD

**Issue by rgaudin** [kiwix/maintenance#102]
Given the number of readers with have and the dependencies of those to the `zimlib`, `kiwixlib` and the `kiwix-tools` (`serve` mostly), it would be very handy to be *notified* when a new release of any of those is published.

Any subscription mechanism could work. I think the easiest path would be an RSS feed built from the `/release` folder hierarchy.

**Comment by kelson42** [comment]
@rgaudin I propose to use https://github.com/amsehili/genRSS and create a feed.xml file each hour in each directory in release/ for openzim and kiwix.
