### ISSUE TITLE
Cleanup tmp.kiwix.org/ci periodically

### ISSUE THREAD

**Issue by kelson42** [kiwix/maintenance#104]
@rgaudin @mgautierfr What about deleting everything older than a month?

**Comment by rgaudin** [comment]
Good to me. If it's still too large we can discuss shorter delays.

**Comment by mgautierfr** [comment]
Good to me also. Even if the file is needed by the CI, it will be recreated.

**Comment by kelson42** [comment]
Fixed in https://github.com/kiwix/maintenance/commit/e20e10cb159ea85b66c6b901a9052a03b5bb2976
