### ISSUE TITLE
How to publish ZIM files without having them in the catalog

### ISSUE THREAD

**Issue by kelson42** [kiwix/maintenance#122]
We need a way to run the Zimfarm on recipe without having to automatically publish the result in our server/library.

**Comment by kelson42** [comment]
@rgaudin What about creating `/zim/.dev/` on download.kiwix.org and secure everything which comes in it won't be part of the official catalog?

**Comment by rgaudin** [comment]
yes, I think that a new _warehouse path_ destination is the way to go for now. As for the name, I'll let you choose it but personnaly, I'd prefer something more explicit than `.dev/`. Maybe something like `private/` ?

**Comment by kelson42** [comment]
Starting the directory with a dot makes it hidden for web servers.

**Comment by kelson42** [comment]
We need that now because we are a few days ago of new ZIM files delivered for Endless

**Comment by kelson42** [comment]
@rgaudin Or maybe better `.noindex/endless` and `.noindex/dev`?

**Comment by kelson42** [comment]
`.hidden` directory has been put on http://download.kiwix.org/zim and Zimfarm has been adapted to be able to publish to it.
