### ISSUE TITLE
Prepare letsencrypt and reverse-proxy to welcome stats.kiwix.org

### ISSUE THREAD

**Issue by kelson42** [kiwix/maintenance#14]
Unfortunately we can not really host that in the cloud, would be to expensive. So we will have to put it on that box two, that should be able to work without problem. I will create the docker-compose and take care of the migration, but we should also update the other dockers.

HTTP should be a redirect to HTTPS

**Comment by florentk** [comment]
Normally, we must just add the new container config in docker-compose and set VIRTUAL_HOST, LETSENCRYPT_* as environnements variables of this container. Lauch `docker-compose up` and everything should work properly. No modification are needed in reverse-proxy image.
