### ISSUE TITLE
Increase security arround SSH deamon

### ISSUE THREAD

**Issue by kelson42** [kiwix/maintenance#184]
We have currently a low security around SSH connection. Beside `fail2ban` which should run on all systems, there is no rule at all.

We would benefit to improve a bit the security:
* Allow only keys and forbids pwd?
* centralize keys/pwd?
* Allow connection only through bastion?
* Doe K8s could easily improve the situation?

A decision should be made.

**Comment by rgaudin** [comment]
> We have currently a low security around SSH connection. Beside `fail2ban` which should run on all systems, there is no rule at all.

Agrees

>     Allow only keys and forbids pwd?

I think you're the only in the team who still uses passwords so if that's OK with you, we could move on with this easily.

>     centralize keys/pwd?

Pros:
- Setting up keys in a single location versus on all servers

Cons:
- More complex configuration on all servers
- New single point of failure

Not sure it's worth the effort/maintenance. We're very few to connect to servers and the benefits are limited.

>     * Allow connection only through bastion?

Pros:
- we can restrict connection to a single incoming IP, ensuring only people connecting through bastion can go through.
- It's the same, single incoming IP to configure once everywhere. Allows more flexible rule on bastion.

Cons:
- In case there's a problem with bastion, we can't reach any server
- Moves the security question from the servers to Bastion. Single server to *harden* is better than multiple but still

>     * Doe K8s could easily improve the situation?

I don't know enough about it honestly but I believe it should help as everything would at least be centralized on the same public host so we could enforce stuff on the entrypoint. Definitely requires some research or insight from someone with k8s experience.

**Comment by kelson42** [comment]
@rgaudin Might be time to revise this ticket. As you are going to provision new K8s nodes, woukd you be able to document the list of basic operations to do please? Setup of SSH daemon woukd be part of it.

**Comment by kelson42** [comment]
@rgaudin I guess this has been fixed with new bastion and #224 ?

**Comment by rgaudin** [comment]
I think we can consider it fixed, although behavior is now different:

- We have several servers now
- SSH is still working mostly the same on all, but:
  - only using keys (no password)
  - only infra-maintainers have access: 2 people
 - remote access to the server has been removed
 - files can still be uploaded by scp and sftp but only to a limited number of locations, using a single user (identified with a key) and there is no shell for it.
