### ISSUE TITLE
wikibooks_en_all_maxi redirect is not functioning

### ISSUE THREAD

**Issue by Popolechien** [kiwix/maintenance#187]
wikibooks_en_all_maxi.zim (as listed on the wiki) should normally point to the last available zim file (https://mirror.download.kiwix.org/zim/wikibooks/wikibooks_en_all_maxi_2021-03.zim) but instead returns "unavailable".

https://library.kiwix.org/wikibooks_en_all_maxi works on library.kiwix.org so I don't know if it also impacts the cardshop or not.

**Comment by kelson42** [comment]
Most of the ZIM download redirects are not working. Serious problem.

**Comment by kelson42** [comment]
works now, but I have done nothing. Not explanation why it failed.
