### ISSUE TITLE
Update to latest nginx-proxy

### ISSUE THREAD

**Issue by rgaudin** [kiwix/maintenance#196]
The nginx-proxy container and its letsencrypt companion have evolved and moved to [a new org](https://github.com/nginx-proxy/) on Github. We are now using those images on pinned, **old** versions.

At some point, we should update to the newer major releases of both images to stay up to date.

**Comment by kelson42** [comment]
@rgaudin Do you know how the migration to K8s will impact this ticket? I wonder if we will still nee both of these containers?

**Comment by rgaudin** [comment]
We won't be using neither of the two container (nginx and letencrypt companion). We can probably close this
