### ISSUE TITLE
File not visible in library

### ISSUE THREAD

**Issue by Popolechien** [kiwix/maintenance#198]
[canadian_prepper_surviving-disaster.zim](https://farm.openzim.org/recipes/canadian_prepper/edit) was completed two weeks ago and moved to /videos yet cannot be seen on library.kiwix.org

**Comment by kelson42** [comment]
@Popolechien Because it does not respect the format (not date in the filename).

**Comment by kelson42** [comment]
I have renamed the file manually to `canadian-prepper_en_surviving-disaster_2021-12.zim`. It should be added to the library next night. In the future the CMS should secure the ZIM filename is "correct".
