### ISSUE TITLE
mirrors.html seems not to be updated one time a day like it should

### ISSUE THREAD

**Issue by kelson42** [kiwix/maintenance#23]
http://mirror.download.kiwix.org/mirrors.html date is 7 november.

**Comment by florentk** [comment]
Cron has not run script because he had a wrong name ('.' in end file name is not accepted ...). Is fix in cb6960b and container is restarted.

**Comment by kelson42** [comment]
@florentk Are your really sure it work, http://mirror.download.kiwix.org/mirrors.html seems not to have been updated last night?

**Comment by florentk** [comment]
@kelson42 je l'ai mis toute les heures comme tu m'as dit, mais là il tourne depuis deux jours, donc il n'a pas pu encore actualiser mirrors.html

**Comment by kelson42** [comment]
@florentk tu peux créer une entrée cron/script séparée stp pour la mise a jour de ce fichier `mirrors.html`. C'était le cas sur l'ancien serveur si je ne me trompe !

**Comment by florentk** [comment]
@kelson42  je vais voir ça, mais c'était sur l'ancien serveur c'etait dans le script. J'ai jamais eu accès à la configuration du cron sur l'ancien serveur, car je crois que c'est dans le crontab du root et j'ai pas la permission.

**Comment by florentk** [comment]
le dernier scan des miroirs à duré 36 minutes

**Comment by kelson42** [comment]
L'entrée ressemble à cela:
`30   3   *   *   *    mb mirrorlist -f xhtml | grep -v "href=\"\"" > /var/www/download.kiwix.org/mirrors.html`

**Comment by florentk** [comment]
fix in 20267d2
