### ISSUE TITLE
MWOffliner for Ted.com

### ISSUE THREAD

**Issue by JonathanJonathanJonathan** [kiwix/maintenance#3]
I would love to create a new Ted.com zim file, that latest one is from 2016-06. I read the Wiki (http://wiki.kiwix.org/wiki/TED) but I couldn't find any source code. 

Is anyone aware of some code that works (or used to work). I may update/fix it so we have an uptodate archive.

**Comment by JonathanJonathanJonathan** [comment]
Found the https://github.com/openzim/ted repo. Is that the one used for the 2016 dump?

**Comment by kelson42** [comment]
@JonathanJonathanJonathan Yes, but it is currently broken because of this bug https://github.com/openzim/ted/issues/3
