### ISSUE TITLE
We need a zimquarantine-docker 

### ISSUE THREAD

**Issue by kelson42** [kiwix/maintenance#30]
ZIM files which are uploaded to `download.kiwix.org` should be checked before being made fully available to download. We have a tool called `zimcheck` (part of the `zim-tools`) aimed to do that checks. This task is about making a Docker container able to use that tool.

This Docker image should:
* Have an input directory (volume)
* Have an output directory (volume)
* Monitor the input directory for ZIM files, check them if `zim-check` and if OK them move them to output directory (keeping the subdirectory hierarchy).
* How the system should behave if an error occurs is a bit unclear so far to me: ideally it should inform the zimfarm if possible (transmit the log), but would prefer to keep that Docker image AFAP independent of the zimfarm. Maybe both requirements are mutually exclusive!?!

Remarks:
* We should check that the move operation (if successful is immediate), otherwise the rest of the toolchain might have problem with incomplete ZIM files

This task depends on https://github.com/openzim/zim-tools/issues/26

**Comment by kelson42** [comment]
@automactic Any ideas about the error handling? Should we have to make it part of the Zimfarm?

**Comment by kelson42** [comment]
* NO_CHECK = just make the move to download.kiwix.org
* NO_QUARANTINE = make the check (log) and move everything to download.kiwix.org even if errors

**Comment by florentk** [comment]
The container is ready : https://hub.docker.com/r/kiwix/zimquarantine with the README

**Comment by kelson42** [comment]
@florentk Would you be able to deploy it please with the option NO_CHECK=1? I think it would be good to have it part of the download.kiwix.org docker compose.

**Comment by florentk** [comment]
@kelson42 before to run the container, I would like confirm with you that all zim file in `/data/zimfarm-warehouse/zim` will be move to `/data/download/zim with overwriting` if file exists in the destination ?

**Comment by kelson42** [comment]
@florentk Yes, and moved to the same directory, so for example: /data/zimfarm-warehouse/zim/tutu/toto.zim will be moved to /data/download/zim/tutu/toto.zim

**Comment by kelson42** [comment]
@florentk Thx for setting that up. If problem I will open a separate ticket.
