### ISSUE TITLE
stats are down since 29/11

### ISSUE THREAD

**Issue by kelson42** [kiwix/maintenance#32]
_From @Popolechien on December 7, 2018 9:56_

But only for download.kiwix.org
Any idea why?

_Copied from original issue: kiwix/web#47_

**Comment by kelson42** [comment]
@florentk Looks like something does not work properly here with the matomo-client Docker.

**Comment by kelson42** [comment]
@florentk you need to fix #33 first IMO

**Comment by florentk** [comment]
fix in 55fef29
