### ISSUE TITLE
Nginx logs should be splited by virtualhosts

### ISSUE THREAD

**Issue by kelson42** [kiwix/maintenance#33]

**Comment by florentk** [comment]
@kelson we need to set TOKEN env variable in docker-compose.yml (line 132). Replace "secret" by the correct token (I don't know this secret token !)

**Comment by kelson42** [comment]
@florentk I have send you the token per email

**Comment by florentk** [comment]
The image reverse proxy enable cron service to executre logrotate. Fix in 0cb54d3
