### ISSUE TITLE
zim directory in zim directory

### ISSUE THREAD

**Issue by kelson42** [kiwix/maintenance#35]
```
$ pwd
/data/download/zim
$ ls -lad zim 
lrwxrwxrwx 1 root root 32 Dec  2 16:37 zim -> /var/www/download.kiwix.org/zim/
```

@florentk I suspect you have added it, but of course this is wrong and I have removed it. Any reason why we have this link here?

**Comment by kelson42** [comment]
@florentk strange, why is that needed exactly? We should find an other way to deal with the pb.

**Comment by florentk** [comment]
@kelson42 I have checked that, and finally delete this unnecessary link
