### ISSUE TITLE
http://warehouse.cardshop.hotspot.kiwix.org/ opens download.openzim.org

### ISSUE THREAD

**Issue by kelson42** [kiwix/maintenance#36]
If no virtualhost is configured for a domain, it should returns 404.

**Comment by florentk** [comment]
@kelson42 We need to set  VIRTUAL_HOST env variable on running the associate image, but is not me who started this container. We need to add a docker-compose for this.

**Comment by kelson42** [comment]
@rgaudin ?

**Comment by rgaudin** [comment]
@florentk, Warehouse has no HTTP service at the moment (FTP only) so as @kelson42 suggested, it's a general issue, not warehouse specific.

Fixed in #40

**Comment by kelson42** [comment]
@florentk @rgaudin Y'a pas moyen d'avoir juste un 404?!

**Comment by rgaudin** [comment]
@kelson42 c'est précisement ce que fait la PR
