### ISSUE TITLE
mirror.download.kiwix.org cert seems not to be created properly

### ISSUE THREAD

**Issue by kelson42** [kiwix/maintenance#4]
```
docker-compose restart letsencrypt
```

Does not allow me to connect with a working SSL layout to https://mirror.download.kiwix.org/.

It seems the certificates are not generated properly in `data/certs/mirror.download.kiwix.org/`

```
# ls mirror.download.kiwix.org/
account_key.json
```

**Comment by florentk** [comment]
I had modified nginx sites config to accept challenge,  now it works : https://mirror.download.kiwix.org/
For moment, I disable download.openzim.org and tmp.kiwix.org domains. I will enable it when we will switch DNS
