### ISSUE TITLE
How is mirrorbrain database initialized

### ISSUE THREAD

**Issue by kelson42** [kiwix/maintenance#42]
I do not see anything about that in the Docker images. The SQL is there  `mirrors-postgresql.sql` but not run anywere looks like?

**Comment by florentk** [comment]
@kelson42  The database is initialized in `init_mirrorbrain_db.sh` script. The dump file `mirrors-postgresql.sql` is used line 17.

**Comment by kelson42** [comment]
@florentk thx, can not explain why I didn't found it :(
