### ISSUE TITLE
Visual editor does not work at all on Kiwix welcome page

### ISSUE THREAD

**Issue by kelson42** [kiwix/maintenance#44]
I don't know if other pages are impacted, but I suspect yes. This is not a problem with the RAM.

**Comment by florentk** [comment]
probably caused by a conflict with a new extension, I confirm that quickly

**Comment by florentk** [comment]
moved to correct issues list : https://github.com/openzim/mediawiki-docker/issues/17

**Comment by florentk** [comment]
Visual editor on Openzim works now (with more RAM),. But for me, no button to modify page in Kiwix wiki to test Visual Editor

**Comment by florentk** [comment]
After many test, it seem that Visual Editor works on welcome page, but it's very very very slow to load the first time.

**Comment by kelson42** [comment]
@florentk You mean the Parsoid server is slow? But you don't know why (cpu, ram, io)?

**Comment by florentk** [comment]
@kelson42 no, I think is the Wikimedia application that is slow, Parsoid wait a response from Wikimedia API. I have tested, all Wiki become slow. I suspect a concurent database access problem but I can not verified that.

**Comment by kelson42** [comment]
@florentk I don't understand which Wikimedia service we rely one. We should not. Which API/URL are we talking about?

**Comment by florentk** [comment]
@kelson42 Is this API/URL (but also other) : 
```
2019-02-03 01:16:27 kiwix kiwix wiki 127.0.0.1 - - [03/Feb/2019:01:16:26 +0000] "GET /w/api.php?format=json&action=query&prop=info%7Crevisions&rawcontinue=1&rvprop=content%7Cids%7Ctimestamp%7Csize%7Csha1%7Ccontentmodel&rvslots=main&revids=30321 HTTP/1.1" 200 6121 "-" "Parsoid/0.10.0+git"
```

**Comment by florentk** [comment]
@kelson42 You can make a test to reproduce the bug : 
- Go to main page with a logged account
- Lauche visual editor -> progress bar blocked
- Run immediatly `curl -v https://wiki.kiwix.org/wiki/` -> error after timeout

**Comment by kelson42** [comment]
@florentk OK, but this is a request to our wiki!? Do you mix "wikimedia" with "mediawiki"?

**Comment by kelson42** [comment]
@florentk I think that Mediawiki is slower as it should. One of the reason I have identified is that it seems that php7-fpm seems not to be configured at all to have an opcache https://mnt-tech.fr/blog/opcache-configuration-et-fonctionnement/. This would probably make quite a difference. Would you be able to activate in in `mediawiki-docker`? Otherwise have you been able to reproduce the problem locally with Kiwix data on your computer?

**Comment by kelson42** [comment]
An other link https://laravel-news.com/php-opcache-docker

**Comment by kelson42** [comment]
@florentk I have created a PR to help to fix this https://github.com/openzim/mediawiki-docker/pull/18

**Comment by florentk** [comment]
@kelson42 ok, this seems to be a good trail, I look that this week.

**Comment by florentk** [comment]
I get this error :  `apierror-visualeditor-docserver-http: HTTP 406. `

**Comment by florentk** [comment]
fix in b0edafec

**Comment by kelson42** [comment]
@florentk As far as I can see the problem is still there. Otherwise have you been able to reproduce the problem locally with Kiwix data on your computer?

**Comment by florentk** [comment]
@kelson42 I don't reproduce problem with Openzime wiki data on my computer. And I don't have Kiwix data to test on my computer.

**Comment by florentk** [comment]
@kelson42 I reproduce this bug on my computer,  it seems it's related with the Translate extension. I re-open the ticket here : https://github.com/openzim/mediawiki-docker/issues/17

**Comment by florentk** [comment]
https://github.com/openzim/mediawiki-docker/issues/21 fix this issue

**Comment by kelson42** [comment]
This has been fixed
