### ISSUE TITLE
Massive SPAM problem on wiki.kiwix.org

### ISSUE THREAD

**Issue by kelson42** [kiwix/maintenance#49]
Since the 28 January 2019.

See:
https://wiki.kiwix.org/w/index.php?title=Special:RecentChanges&limit=250

**Comment by kelson42** [comment]
@florent, have you changed the config at that time?

**Comment by kelson42** [comment]
We seem to have a similar problem with wiki.openzim.org

**Comment by florentk** [comment]
@kelson42 No modification at that time, it's very strange

**Comment by kelson42** [comment]
@florentk I suspect this is because of #48. Let see how things will evolve.

**Comment by kelson42** [comment]
@florentk The problem is still there, we need to understand why? Do we have changed the configuration or maybe the emailing works better know so people can validate their accounts?

**Comment by florentk** [comment]
@kelson42 yes, but I can't understand why. the protection with CAPTCHA is may be not strong enough ?

**Comment by kelson42** [comment]
@florentk Maybe... We had a protection to avoid connection from TOR nodes, does that work properly?

**Comment by florentk** [comment]
@kelson42 TorBlock is active : 
https://wiki.kiwix.org/wiki/Special:Version#mw-version-ext-antispam-TorBlock
https://wiki.openzim.org/wiki/Special:Version#mw-version-ext-antispam-TorBlock

**Comment by kelson42** [comment]
@florentk I have changed the captcha system on the Kiwix wiki, lets have a look if this works better.

**Comment by kelson42** [comment]
Situation seems OK currently... for both... I don't really understand why. But OK.
