### ISSUE TITLE
Wikifundi on Sloppy is suspended

### ISSUE THREAD

**Issue by kelson42** [kiwix/maintenance#52]
The container seem to have been removed, but none has been created new!

**Comment by kelson42** [comment]
@florentk Do you think I have done something stupid on Sloppy which might have caused that pb?

**Comment by kelson42** [comment]
@florentk We were short of a few hundreds of MB. You should have 2x2GB now... but why both failed... and not only one?

**Comment by florentk** [comment]
@kelson42 Because both are created in one time by sending this config file : https://github.com/openzim/wikifundi/blob/master/sloppy-full-mirroring.json

**Comment by kelson42** [comment]
@florentk They are back. Thx
