### ISSUE TITLE
wiki.kiwix.org is not updated anymore by the library docker instance

### ISSUE THREAD

**Issue by kelson42** [kiwix/maintenance#55]
This is since November and I think the problem comes from the fact that the perl code to edit on Mediawiki is outdated.

**Comment by kelson42** [comment]
@florentk Do you think we could replace it with https://github.com/mwclient/mwclient ?

**Comment by florentk** [comment]
@kelson42 what does Travis say?

**Comment by kelson42** [comment]
@florentk This has nothing do with Travis. This fails https://github.com/kiwix/maintenance/blob/master/library-docker/bin/manageContentRepository.pl#L207. As a consequence this page https://wiki.kiwix.org/w/index.php?title=Template:ZIMdumps/content&action=history has not been updated since novembre...

**Comment by florentk** [comment]
@kelson42 ok, I had misunderstand, I have to watch this more closely

**Comment by kelson42** [comment]
After asking a few people from the Wikipedia community, might be that the best approach would be to use https://github.com/Git-Mediawiki/Git-Mediawiki. If it works this would allow us to make update quite transparently.

**Comment by florentk** [comment]
@kelson42 nice, I testing that. A litlle script bash should do the work ?

**Comment by kelson42** [comment]
@florentk I have tested a bit... imo it won't work because MW authentication has changed recently. Mabe you can juste make a small ython script which takes a file in argument and update the wiki argument with its content.

**Comment by florentk** [comment]
fix in 64fedc2
