### ISSUE TITLE
Reverse proxy seems to not allow any compression

### ISSUE THREAD

**Issue by kelson42** [kiwix/maintenance#57]
```
$ curl -i https://library.kiwix.org/ 2>/dev/null | grep -i "vary"
$ 
```

As a consequence, none of the content delivered is compressed, this is a waste of bandwidth and impacts seriously the whole user experience (everything slower).

**Comment by florentk** [comment]
@kelson42  it's ok now ?

**Comment by kelson42** [comment]
@florentk No, see for example http://www.ipmango.com/http/deflate

**Comment by kelson42** [comment]
@florentk This might be interesting to read https://github.com/jwilder/nginx-proxy/issues/139

**Comment by kelson42** [comment]
@florentk Ideally the proxy should just take whatever comes from the client/backend_web_server and forward it. I'm not reallyin favour of having the reverse-proxy recompressing stuff if this is not done by the backend.

**Comment by florentk** [comment]
@kelson42  I've updated the configuration, the compression seem works now

**Comment by kelson42** [comment]
@florentk At a first sight, seems to work better indeed. How have you achieved to do that? I see no commit!

**Comment by florentk** [comment]
@kelson42 I va forgot the commit, is here : 4c2f8c0949

**Comment by kelson42** [comment]
@florentk Good, last question: why we have matomo_web, as kiwix/matomo has already a web server and would be anyway reversed proxied behind our front revers proxy?

**Comment by florentk** [comment]
@kelson42 I've follow the exemple provided by matomo/docker : https://github.com/matomo-org/docker/blob/master/.examples/nginx/docker-compose.yml
I would have liked use our front reverse-proxy instead a other nginx container, but the configuration is not easy

**Comment by kelson42** [comment]
@florentk I have moved the question to #65. Thx for fixing the compression stuff on the reverse proxy.
