### ISSUE TITLE
Update mirrors.hml

### ISSUE THREAD

**Issue by kelson42** [kiwix/maintenance#6]
It seems there is no code migrated to docker to update `https://mirror.download.kiwix.org/mirrors.html`.

This code is in the `cron` on the old server and looks like following:
```
 mb mirrorlist -f xhtml | grep -v "href=\"\"" > /var/www/download.kiwix.org/mirrors.html
```

It should be put IMO in the `mirrorbrain-update` container.

**Comment by florentk** [comment]
fix in 440ef3e
