### ISSUE TITLE
Matomo geoip system is not properly configured

### ISSUE THREAD

**Issue by kelson42** [kiwix/maintenance#60]
AFAIK we simply share our IPs with a third party entity, this is not acceptable from a privacy perspective. We should use our own server to determine the location.

**Comment by kelson42** [comment]
I have asked a question upstream, not sure my understanding is right. https://github.com/matomo-org/docker/issues/153

**Comment by florentk** [comment]
@kelson42 The nginx/fpm variante image contain the GeoIP city database : https://github.com/matomo-org/docker/blob/master/fpm/Dockerfile#L81
The API PHP MaxMind just allows to read the local database : 
 https://packagist.org/packages/geoip2/geoip2
