### ISSUE TITLE
Provide access-control header for download.kiwix.org

### ISSUE THREAD

**Issue by Jaifroid** [kiwix/maintenance#61]
I think it would be helpful to clients running in Web context or from localhost or file:// URLs if download.kiwix.org could provide a permissive access control header:

`Access-Control-Allow-Origin: *`

I can currently only get data from download.kiwix.org in app context, but not in any browser context except Internet Explorer 11 (which allows cross-origin when the user explicitly allows active content to run).

I don't know all the options, but https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS provides good examples.

**Comment by Jaifroid** [comment]
Thanks, guys!

**Comment by Jaifroid** [comment]
Just quickly to say that this is now working well. I no longer get CORS errors when accessing the server from non-app contexts, which is great.

**Comment by kelson42** [comment]
@Jaifroid great :)
