### ISSUE TITLE
A few content download are counted twice

### ISSUE THREAD

**Issue by kelson42** [kiwix/maintenance#62]
wikipedia_en_all.zim AND wikipedia_en_all_20XX-YY.zim

**Comment by kelson42** [comment]
@rgaudin Do you know with the Matomo log indester if we could ignore Permanent redirects but take temporary redirects in account?

**Comment by rgaudin** [comment]
We are using 

```
  --enable-http-redirects
                        Track HTTP redirects (status code 3xx except 304)
```

We could either not use it or I could easily patch it if you want to exclude `301` and `308` response. We are already patching this script…

Let me know

**Comment by kelson42** [comment]
@rgaudin I'm not sure how to proceed, but I want to keep tracking the redirections (they are 302) generated by Mirrorbrain to one of the mirrors (for obvious mirror), but I don't want to track the redirection which are in the `.htaccess` (302 as well).

In the past, with my custom log indgester, we were generating 302 in the .htaccess but with a no-cache header or something like this (so in fact it was working like a 302)... but that way I was able to make the differrence and ignore all the one from our .htaccess.

**Comment by kelson42** [comment]
The best solution I see:
* Return 301 (instead of 302) in the .htaccess
* Configure Apache to have a no-cache header for all 301 responses
* Hack the Matomo indgesting script

@rgaudin You have something better in mind?

**Comment by kelson42** [comment]
Ok, working on my plan...
