### ISSUE TITLE
Why do we have an extra reverse-proxy for Matomo

### ISSUE THREAD

**Issue by kelson42** [kiwix/maintenance#65]
@florentk Good, last question: why we have matomo_web, as kiwix/matomo has already a web server and would be anyway reversed proxied behind our front revers proxy?

@kelson42 I've follow the exemple provided by matomo/docker : https://github.com/matomo-org/docker/blob/master/.examples/nginx/docker-compose.yml
I would have liked use our front reverse-proxy instead a other nginx container, but the configuration is not easy

**Comment by kelson42** [comment]
@florentk I think you have to be behind our main reverse proxy anyhow! You can not have two reverses proxy listening on the same port and same IP! Something is really unclear to me here.

**Comment by florentk** [comment]
@kelson42 Is not the same IP, the container of matomo_web do not expose the port 80.
Look in the docker-compose of matomo-server, We have an host name alias : `stats` for matomo_web and the container is in the network `kiwix.org`. Then all container in this network (like the reverse-proxy) resolve stats.kiwix.org as the private IP associated to matomo_web container. When the reverse-proxy find  `VIRTUAL_HOST=stats.kiwix.org`  for matomo_web, it resolve this private IP and create the configuration to relayed all publics requests  to the matomo_web container.

**Comment by kelson42** [comment]
@florentk thx
