### ISSUE TITLE
Where are stored custom Matomo logo & favicon

### ISSUE THREAD

**Issue by kelson42** [kiwix/maintenance#67]
I want to upload a custom logo and favicon, but I'm not sure this will stay persistent. The way how the volumes are configured seems a bit strange to me.

**Comment by florentk** [comment]
Actually matomo_web and matomo_app must be share the same volume (matomo_web to serve all static files and matomo_app to execute PHP codes). I name this volume `appdir`.  As it is not a path, docker create a volume at this location : `/var/lib/docker/volumes/matomo-server-docker_appdir/_data`. But I can mount the volume on a other path, like `/data/matomo/web`. As you wish.

**Comment by florentk** [comment]
@kelson42 to answer your question, if theses files has copied in /var/www/html in the `app` container,  this will stay persistent

**Comment by kelson42** [comment]
@florentk Thank you for the explanation. I better understand. `/var/lib/docker/volumes/matomo-server-docker_appdir/` is not interesting to us as it does not contain to a large user generated content so why having it exported in a volume. The logo and favicon are stored in `/var/lib/docker/volumes/matomo-server-docker_appdir/_data/misc/user` so we should only map this as an external volume to `/data/matomo/data/`. I hope that way we have exported properly all the user-generated data and we can backup them properly. Do you confirm?

**Comment by florentk** [comment]
fix in 426ff98
