### ISSUE TITLE
Introduce download.openzim.org to Matomo

### ISSUE THREAD

**Issue by kelson42** [kiwix/maintenance#68]

**Comment by kelson42** [comment]
@florentk If you could help to get that done quickly, would be really helpful.

**Comment by florentk** [comment]
fix in 4ea403b

**Comment by kelson42** [comment]
@florentk thx!

**Comment by kelson42** [comment]
@florentk Are you sure it works? https://stats.kiwix.org/index.php?module=CoreHome&action=index&date=yesterday&period=day&idSite=6&updated=2#?idSite=6&period=day&date=yesterday&category=Dashboard_Dashboard&subcategory=1 seems to have no visitor and it seems the whole site is not available for public (if I'm not logged in)

**Comment by kelson42** [comment]
@florentk I have fixed the pb of access

**Comment by florentk** [comment]
@kelson42 I have tested, for me it's works, but we have few visitors

**Comment by kelson42** [comment]
@florentk You are right, I see my own visits now. Sorry. All good.
