### ISSUE TITLE
https://download.openzim.org fails

### ISSUE THREAD

**Issue by kelson42** [kiwix/maintenance#7]
I have migrated the service but seems impossible to get the SSL cert configured properly.

**Comment by kelson42** [comment]
I have updated the `docker-compose.yml` but I still get:

```
# docker-compose restart letsencrypt
ERROR: No containers to restart
```

Do I have broken something?

**Comment by florentk** [comment]
This is you had moved docker-compose.yml to a other directory name. By default, Docker get directory name  to set the "project name". Here "kiwix". But now, the directory is `code` and if you not specify the project name, it search the project `code`. To fix this : `docker-compose -p kiwix  restart`

**Comment by kelson42** [comment]
@florentk I have renamed the directory to get everything works like before but do we have a way to update the containers to get them fit a new location of `docker-compose` file?

**Comment by florentk** [comment]
@kelson42 as I understand it, it's not the docker-compose file that counts but the project name. So, I just saw that now it's in a directory `kiwix`, so it takes as before the project name`kiwix`

**Comment by florentk** [comment]
@kelson42 but `download.openzim.org` still doesn't works. It's strange  because the configuration is exactly the same that mirror.download.kiwix.org

**Comment by kelson42** [comment]
@florentk Ok... Lets hope you can fix it. Waiting to this to migrate next service :)
