### ISSUE TITLE
/var/local/vhost.d/ content should be in the git repo

### ISSUE THREAD

**Issue by kelson42** [kiwix/maintenance#78]
@florentk IMO!?

**Comment by florentk** [comment]
maybe in /data/var ?

**Comment by kelson42** [comment]
@florentk Any reason why it should not be in the git? /data/var is not!

**Comment by florentk** [comment]
@kelson42 because all the other volumes are not mounted in the git !! Why this one ?

**Comment by florentk** [comment]
@kelson42 in fact, this mount is for share files between reverse-proxy and letsencrypt containers. So, I prefer use a volume mounted in a path managed by docker. fix in 36f34db
