### ISSUE TITLE
Weaknesses in library-docker

### ISSUE THREAD

**Issue by kelson42** [kiwix/maintenance#8]
`library.kiwix.org.xml` is not generated. This is how it is on the old serveur:

```
/var/www/kiwix/tools/tools/scripts/manageLibraryKiwixOrg.pl --source=/var/www/download.kiwix.org/library/library_zim.xml > library.kiwix.org.xml
```
This should be synced one time a day automatically

On the top of that, the kiwix-serve should be run in a while true loop, to avoid the whole service to dies if there is a bug in kiwix-serve causing a crash. Currently we run:
```
 while [ 42 ] ; do kiwix-serve --port=4242 --library --interface=lo --threads=16 --verbose library.kiwix.org.xml ; sleep 1 ; done
```

**Comment by florentk** [comment]
fixed in #7a16993
