### ISSUE TITLE
library.kiwix.org multizim fulltext search and suggestions is too slow (causes 504 gateway timeout)

### ISSUE THREAD

**Issue by Popolechien** [kiwix/maintenance#85]
Edit: I also gate 502 Bad Gateway

**Comment by kelson42** [comment]
@Popolechien Do you mean a general one or your search just fails?

**Comment by Popolechien** [comment]
@kelson42 I'm not sure I understand the question, but whenever I type a search term in the library.kiwix.org search bar (presumably searching for a specific zim file, e.g. typing "history"), I get the 502/504.
Yet when I'm in a specific zim and I use it, no problem. Say, I'm in the history selection and start typing "battle of" then the search will naturally offer a list of battles of to choose from.

Also once I get the 504 on the main page it does not prevent the individual zim files from working (e.g. I have two tabs: one on the main page has crashed/504'd on me, but the other one that's open on History or TOP I can navigate without any problem). So the bug affects only library.kiwix.org but not its subpages, e.g. http://library.kiwix.org/wikipedia_fr_history_nopic_2019-08/A/index)

**Comment by kelson42** [comment]
@Popolechien Thank you, you have answered the question

**Comment by kelson42** [comment]
I'm closing this ticket as the monitoring a a lot more stable with the last kiwix-serve release. That said, the search is still too slow. This is mostly because retrieving the snippet is slow, this should be a lot of faster with ZIM using ZStandard.
