### ISSUE TITLE
`manageContentRepository.pl` is called in none of the docker images

### ISSUE THREAD

**Issue by kelson42** [kiwix/maintenance#9]
It should run one time a day, here is how the cron looks like on the old server:
```
30   2   *   *   *    cd /var/www/kiwix/tools/tools/scripts ; ./manageContentRepository.pl --wikiPassword=42 --writeWiki --writeHtaccess --writeLibrary --deleteOutdatedFiles
```

This should be introduced in the library Dockerfile.

**Comment by kelson42** [comment]
This is a blocker for proper implementation of #8

**Comment by florentk** [comment]
@kelson42  I have a depency problem for these module : 

- `Kiwix::PathExplorer`
- `Mediawiki::Mediawiki`

cpan don't find these modules. How I can install them  ?

**Comment by florentk** [comment]
@kelson42 I have successfully installed the dependencies, but I got this error : 
`Experimental keys on scalar is now forbidden at /usr/share/perl5/Mediawiki/Mediawiki.pm line 1201, <DATA> line 1.`

**Comment by florentk** [comment]
@kelson42 I had an other error : 
`
Experimental shift on scalar is now forbidden at /usr/local/bin/manageContentRepository.pl line 422, near "])"
Experimental shift on scalar is now forbidden at /usr/local/bin/manageContentRepository.pl line 423, near "])"
`
Sorry I don't code in Perl

**Comment by kelson42** [comment]
J'ai commité un fix ac58b80 qui normalement corrige le pb

**Comment by kelson42** [comment]
Made a new fix, this time it should be good b4b61f1

**Comment by florentk** [comment]
@kelson42 encore une autre erreur : 
```
Can't use string ("4") as an ARRAY ref while "strict refs" in use at /usr/local/bin/manageContentRepository.pl line 421, <DATA> line 1. 
```

**Comment by kelson42** [comment]
vraiment désolé... j'ai fait le fix "de la derniere chance".

**Comment by florentk** [comment]
@kelson42 with the last fix, I got this error : 

`Thread 1 terminated abnormally: /var/www/download.kiwix.org/zim/ encountered a second time at /usr/share/perl/5.24/File/Find.pm line 103, <DATA> line 1.`

But the script does not leave, but run whithout output, this is right ?

**Comment by kelson42** [comment]
No, it is not right

**Comment by kelson42** [comment]
@florentk I think I have finally fix the pb with the perl, but the image/container has still other problems.

**Comment by kelson42** [comment]
This seems to be fixed now
