### ISSUE TITLE
Matomo is partly not updated anymore since 4 days

### ISSUE THREAD

**Issue by kelson42** [kiwix/maintenance#91]
For wiki.kiwix.org and wiki.openzim.org... and I have no clue why!

**Comment by florentk** [comment]
I presume that is since runJob is running every minute. I desactivate that for openzim wiki to confirm.

**Comment by kelson42** [comment]
@florentk maybe... but I hardly see how one could influence the other...

**Comment by florentk** [comment]
@kelson42 I downgraded Matomo Analytics Extension, this seem work now (for Openzim and I just restart kiwix).

**Comment by kelson42** [comment]
@florentk Seems to work. Thx
