### ISSUE TITLE
Android translations are producing invalid xml

### ISSUE THREAD

**Issue by macgills** [kiwix/maintenance#96]
When trying to translate
```
<plurals name="books_count">
    <item quantity="one">%d book</item>
    <item quantity="other">%d books</item>
  </plurals>
```
what is produced is
```
<plurals name="books_count">
```
With no content or closing tag.

Additionally `'`s are being double escaped.
invalid : `\\'`
valid     : `\'`

**Comment by kelson42** [comment]
The way to update the translation has changed. It is now commited directly by Translatewiki bot to the kiwix-android repository.
