### ISSUE TITLE
Add security to secure that the placeholder "%ss" are not removed from translation files

### ISSUE THREAD

**Issue by kelson42** [kiwix/maintenance#97]
Otherwise the Android app might crash

**Comment by macgills** [comment]
In [this PR](https://github.com/kiwix/kiwix-android/pull/1264) there is an error with hungarian
   `<string name="speech_prompt_text">A kereséshez beszélj</string>`
this should be a format string
  `<string name="speech_prompt_text">Speak to search %s</string>`
If the 'String.format' call were to happen to the latter there would be a guaranteed crash from a `java.util.IllegalFormatException`

If there are any [format args](https://dzone.com/articles/java-string-format-examples) they must be preserved

**Comment by kelson42** [comment]
Fixed in https://github.com/kiwix/maintenance/commit/3e834f42ea006e1181fe693b86c8402ab9fd70c2

**Comment by kelson42** [comment]
It is still not working fine

**Comment by kelson42** [comment]
@Nikerabbit works on fix it in the new kiwix-android translation importer

**Comment by kelson42** [comment]
We don't do translation in this repo anymore.
